spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lm_cloud_admin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: qiao
    password: 1100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ????/?????
    show-sql: true      # ?????SQL??
    properties:
      hibernate:
        format_sql: true # ???SQL??
        dialect: org.hibernate.dialect.MySQL8Dialect